// Auto-generated Audio Asset Map
export const audioMap = {
  "What if Alex packed one more t-shirt? How many outfits would that unlock?": "/assets/audio/wonder_teaser.mp3",
  "key:wonder_teaser": "/assets/audio/wonder_teaser.mp3",
  "Welcome to Patterns and Systematic Lists! Ready to crack the rule behind any sequence, and list every single possibility without missing one? Let's roll!": "/assets/audio/home_intro.mp3",
  "key:home_intro": "/assets/audio/home_intro.mp3",
  "Robo is packing for a trip. Alex has 3 t-shirts and 2 pairs of shorts, and says: There are only 5 outfits I can make, because 3 plus 2 is 5. Is that actually true? And Robo notices the staircase outside grows by 2 steps every floor: 2, 4, 6, 8... will it ever land exactly on 25 steps?": "/assets/audio/wonder_prompt.mp3",
  "key:wonder_prompt": "/assets/audio/wonder_prompt.mp3",
  "Slide 1: Meet the Pattern Family! Patterns are sequences that follow a hidden rule. Meet Arithmetic, adding or subtracting the same number every time. Growing Figures, shapes that add a fixed number of tiles each step. Repeating patterns, that cycle in a loop. And Systematic Lists, where we organise every possible outcome in careful order so nothing is missed and nothing repeats!": "/assets/audio/story_slide_1.mp3",
  "key:story_slide_1": "/assets/audio/story_slide_1.mp3",
  "Welcome to the Pattern Lab! Adjust the starting number and the step size, and watch the sequence grow term by term. Can you build the target pattern shown on screen?": "/assets/audio/station_a_intro.mp3",
  "key:station_a_intro": "/assets/audio/station_a_intro.mp3",
  "Slide 3: Real World Pattern Powers! Look at staircases that rise by the same height each step, tiling patterns on a floor, ice cream combos at a shop, and PIN codes on a lock. Every one of these hides either a growing pattern or a systematic list waiting to be counted!": "/assets/audio/story_slide_3.mp3",
  "key:story_slide_3": "/assets/audio/story_slide_3.mp3",
  "Slide 4: Finding the Missing Term! Detective Time! A pattern goes 4, 9, 14, 19, and then a missing term. Each term adds 5. So the missing term is 19 plus 5, which is 24! The same detective thinking works for systematic lists too: count what you know, then use the rule to find what's missing.": "/assets/audio/story_slide_4.mp3",
  "key:story_slide_4": "/assets/audio/story_slide_4.mp3",
  "Slide 2: The Golden Rule of Systematic Listing! When listing outcomes, always work in the same order, for example smallest to largest, or first list to second list. Never jump around. And here's the shortcut: if there are 3 choices for the first thing and 2 choices for the second thing, the total number of combinations is 3 times 2, which is 6, not 3 plus 2!": "/assets/audio/story_slide_2.mp3",
  "key:story_slide_2": "/assets/audio/story_slide_2.mp3",
  "Choose your world on the map! Beat each world to unlock the next. Earn stars and XP!": "/assets/audio/practice_welcome.mp3",
  "key:practice_welcome": "/assets/audio/practice_welcome.mp3",
  "Station C: Pattern Detective! Use the step rule to work out the missing term hiding in each sequence.": "/assets/audio/station_c_intro.mp3",
  "key:station_c_intro": "/assets/audio/station_c_intro.mp3",
  "Station D: Real-World Pattern Lab! Explore how constant-step patterns show up in staircases, stadium seating, tiling floors, and savings jars!": "/assets/audio/station_d_intro.mp3",
  "key:station_d_intro": "/assets/audio/station_d_intro.mp3",
  "Station B: Systematic List Builder! Tap through the grid in order, row by row, to list every combination between two lists. Watch the total update as you go — it always equals rows times columns!": "/assets/audio/station_b_intro.mp3",
  "key:station_b_intro": "/assets/audio/station_b_intro.mp3",
  "Awesome job! You got it right!": "/assets/audio/correct_cheer.mp3",
  "key:correct_cheer": "/assets/audio/correct_cheer.mp3",
  "Congratulations! You completed the world and earned new stars!": "/assets/audio/world_complete.mp3",
  "key:world_complete": "/assets/audio/world_complete.mp3",
  "Oh no! Out of hearts! Don't worry, try again to master this world!": "/assets/audio/out_of_hearts.mp3",
  "key:out_of_hearts": "/assets/audio/out_of_hearts.mp3",
  "Not quite. Look for the rule between the terms, or multiply the choices at each stage!": "/assets/audio/incorrect_try_again.mp3",
  "key:incorrect_try_again": "/assets/audio/incorrect_try_again.mp3",
  "Your Performance! Amazing work! Let's reflect on what you learned.": "/assets/audio/reflect_intro.mp3",
  "key:reflect_intro": "/assets/audio/reflect_intro.mp3",
  "What is a number pattern, and what do we call the fixed amount added each time?": "/assets/audio/reflect_q1.mp3",
  "key:reflect_q1": "/assets/audio/reflect_q1.mp3",
  "What is the golden rule for finding the total in a systematic list?": "/assets/audio/reflect_q2.mp3",
  "key:reflect_q2": "/assets/audio/reflect_q2.mp3",
  "A number pattern is a sequence of numbers that follows a rule. The fixed amount added or subtracted each time is called the common difference, or the step.": "/assets/audio/reflect_a1.mp3",
  "key:reflect_a1": "/assets/audio/reflect_a1.mp3",
  "How do you find a missing term in the middle or end of a sequence?": "/assets/audio/reflect_q3.mp3",
  "key:reflect_q3": "/assets/audio/reflect_q3.mp3",
  "How do you find the value at any position, like the 10th term, without listing every term?": "/assets/audio/reflect_q4.mp3",
  "key:reflect_q4": "/assets/audio/reflect_q4.mp3",
  "Find the common difference from the terms you know, then add or subtract that step to reach the missing term!": "/assets/audio/reflect_a3.mp3",
  "key:reflect_a3": "/assets/audio/reflect_a3.mp3",
  "Multiply the number of choices at each stage! If there are 3 choices for one thing and 2 for another, the total is 3 times 2, which is 6.": "/assets/audio/reflect_a2.mp3",
  "key:reflect_a2": "/assets/audio/reflect_a2.mp3",
  "Where can you see patterns and systematic lists in real life?": "/assets/audio/reflect_q5.mp3",
  "key:reflect_q5": "/assets/audio/reflect_q5.mp3",
  "Why must we list outcomes in the same order every time instead of jumping around?": "/assets/audio/reflect_q6.mp3",
  "key:reflect_q6": "/assets/audio/reflect_q6.mp3",
  "Use the formula: Term = start + (position minus 1) times step. Plug in the position you need!": "/assets/audio/reflect_a4.mp3",
  "key:reflect_a4": "/assets/audio/reflect_a4.mp3",
  "Staircases, stadium seating, tiling floors, savings that grow each week, ice-cream flavour combos, and PIN or padlock codes!": "/assets/audio/reflect_a5.mp3",
  "key:reflect_a5": "/assets/audio/reflect_a5.mp3",
  "Find how much is added each time. Here, each term increases by 3.": "/assets/audio/w1_q7_hint.mp3",
  "key:w1_q1_hint": "/assets/audio/w1_q1_hint.mp3",
  "Look at this pattern: 2, 5, 8, 11, ___. What comes next?": "/assets/audio/w1_q1_prompt.mp3",
  "key:w1_q1_prompt": "/assets/audio/w1_q1_prompt.mp3",
  "Look at this pattern: 5, 9, 13, 17, ___. What comes next?": "/assets/audio/w1_q2_prompt.mp3",
  "key:w1_q2_prompt": "/assets/audio/w1_q2_prompt.mp3",
  "Working in a fixed order, like smallest to largest, makes sure we never repeat an outcome and never accidentally skip one!": "/assets/audio/reflect_a6.mp3",
  "key:reflect_a6": "/assets/audio/reflect_a6.mp3",
  "Find how much is added each time. Here, each term increases by 4.": "/assets/audio/w1_q9_hint.mp3",
  "key:w1_q2_hint": "/assets/audio/w1_q2_hint.mp3",
  "Find how much is added each time. Here, each term increases by 5.": "/assets/audio/w1_q3_hint.mp3",
  "key:w1_q3_hint": "/assets/audio/w1_q3_hint.mp3",
  "Look at this pattern: 10, 12, 14, 16, ___. What comes next?": "/assets/audio/w1_q4_prompt.mp3",
  "key:w1_q4_prompt": "/assets/audio/w1_q4_prompt.mp3",
  "Look at this pattern: 1, 6, 11, 16, ___. What comes next?": "/assets/audio/w1_q3_prompt.mp3",
  "key:w1_q3_prompt": "/assets/audio/w1_q3_prompt.mp3",
  "Find how much is added each time. Here, each term increases by 6.": "/assets/audio/w1_q5_hint.mp3",
  "key:w1_q5_hint": "/assets/audio/w1_q5_hint.mp3",
  "Look at this pattern: 6, 12, 18, 24, ___. What comes next?": "/assets/audio/w1_q5_prompt.mp3",
  "key:w1_q5_prompt": "/assets/audio/w1_q5_prompt.mp3",
  "Find how much is added each time. Here, each term increases by 2.": "/assets/audio/w1_q4_hint.mp3",
  "key:w1_q4_hint": "/assets/audio/w1_q4_hint.mp3",
  "Look at this pattern: 3, 10, 17, 24, ___. What comes next?": "/assets/audio/w1_q6_prompt.mp3",
  "key:w1_q6_prompt": "/assets/audio/w1_q6_prompt.mp3",
  "key:w1_q7_hint": "/assets/audio/w1_q7_hint.mp3",
  "Find how much is added each time. Here, each term increases by 7.": "/assets/audio/w1_q6_hint.mp3",
  "key:w1_q6_hint": "/assets/audio/w1_q6_hint.mp3",
  "Look at this pattern: 8, 11, 14, 17, ___. What comes next?": "/assets/audio/w1_q7_prompt.mp3",
  "key:w1_q7_prompt": "/assets/audio/w1_q7_prompt.mp3",
  "Look at this pattern: 4, 12, 20, 28, ___. What comes next?": "/assets/audio/w1_q8_prompt.mp3",
  "key:w1_q8_prompt": "/assets/audio/w1_q8_prompt.mp3",
  "key:w1_q9_hint": "/assets/audio/w1_q9_hint.mp3",
  "Find how much is added each time. Here, each term increases by 8.": "/assets/audio/w1_q8_hint.mp3",
  "key:w1_q8_hint": "/assets/audio/w1_q8_hint.mp3",
  "Look at this pattern: 7, 16, 25, 34, ___. What comes next?": "/assets/audio/w1_q10_prompt.mp3",
  "key:w1_q10_prompt": "/assets/audio/w1_q10_prompt.mp3",
  "Look at this pattern: 9, 13, 17, 21, ___. What comes next?": "/assets/audio/w1_q9_prompt.mp3",
  "key:w1_q9_prompt": "/assets/audio/w1_q9_prompt.mp3",
  "Each term adds 4.": "/assets/audio/w2_q1_hint.mp3",
  "key:w2_q1_hint": "/assets/audio/w2_q1_hint.mp3",
  "This pattern is growing: 3, 7, 11, 15, ___. Find the next term.": "/assets/audio/w2_q1_prompt.mp3",
  "key:w2_q1_prompt": "/assets/audio/w2_q1_prompt.mp3",
  "This pattern is growing: 10, 15, 20, 25, ___. Find the next term.": "/assets/audio/w2_q2_prompt.mp3",
  "key:w2_q2_prompt": "/assets/audio/w2_q2_prompt.mp3",
  "Find how much is added each time. Here, each term increases by 9.": "/assets/audio/w1_q10_hint.mp3",
  "key:w1_q10_hint": "/assets/audio/w1_q10_hint.mp3",
  "Each term adds 6.": "/assets/audio/w2_q3_hint.mp3",
  "key:w2_q3_hint": "/assets/audio/w2_q3_hint.mp3",
  "Each term adds 5.": "/assets/audio/w2_q2_hint.mp3",
  "key:w2_q2_hint": "/assets/audio/w2_q2_hint.mp3",
  "This pattern is growing: 15, 18, 21, 24, ___. Find the next term.": "/assets/audio/w2_q4_prompt.mp3",
  "key:w2_q4_prompt": "/assets/audio/w2_q4_prompt.mp3",
  "This pattern is growing: 2, 8, 14, 20, ___. Find the next term.": "/assets/audio/w2_q3_prompt.mp3",
  "key:w2_q3_prompt": "/assets/audio/w2_q3_prompt.mp3",
  "Each term adds 3.": "/assets/audio/w2_q4_hint.mp3",
  "key:w2_q4_hint": "/assets/audio/w2_q4_hint.mp3",
  "Each term adds 7.": "/assets/audio/w2_q5_hint.mp3",
  "key:w2_q5_hint": "/assets/audio/w2_q5_hint.mp3",
  "This pattern is growing: 6, 13, 20, 27, ___. Find the next term.": "/assets/audio/w2_q5_prompt.mp3",
  "key:w2_q5_prompt": "/assets/audio/w2_q5_prompt.mp3",
  "This pattern is shrinking: 50, 46, 42, 38, ___. Find the next term.": "/assets/audio/w2_q6_prompt.mp3",
  "key:w2_q6_prompt": "/assets/audio/w2_q6_prompt.mp3",
  "Each term subtracts 4.": "/assets/audio/w2_q6_hint.mp3",
  "key:w2_q6_hint": "/assets/audio/w2_q6_hint.mp3",
  "Each term subtracts 5.": "/assets/audio/w2_q7_hint.mp3",
  "key:w2_q7_hint": "/assets/audio/w2_q7_hint.mp3",
  "This pattern is shrinking: 60, 57, 54, 51, ___. Find the next term.": "/assets/audio/w2_q8_prompt.mp3",
  "key:w2_q8_prompt": "/assets/audio/w2_q8_prompt.mp3",
  "This pattern is shrinking: 40, 35, 30, 25, ___. Find the next term.": "/assets/audio/w2_q7_prompt.mp3",
  "key:w2_q7_prompt": "/assets/audio/w2_q7_prompt.mp3",
  "Each term subtracts 3.": "/assets/audio/w2_q8_hint.mp3",
  "key:w2_q8_hint": "/assets/audio/w2_q8_hint.mp3",
  "Each term subtracts 6.": "/assets/audio/w2_q9_hint.mp3",
  "key:w2_q9_hint": "/assets/audio/w2_q9_hint.mp3",
  "This pattern is shrinking: 45, 38, 31, 24, ___. Find the next term.": "/assets/audio/w2_q10_prompt.mp3",
  "key:w2_q10_prompt": "/assets/audio/w2_q10_prompt.mp3",
  "This pattern is shrinking: 30, 24, 18, 12, ___. Find the next term.": "/assets/audio/w2_q9_prompt.mp3",
  "key:w2_q9_prompt": "/assets/audio/w2_q9_prompt.mp3",
  "Each term subtracts 7.": "/assets/audio/w2_q10_hint.mp3",
  "key:w2_q10_hint": "/assets/audio/w2_q10_hint.mp3",
  "Subtract any term from the term right after it.": "/assets/audio/w3_q10_hint.mp3",
  "key:w3_q1_hint": "/assets/audio/w3_q1_hint.mp3",
  "Look at this pattern: 4, 7, 10, 13. What number is added each time to get the next term?": "/assets/audio/w3_q1_prompt.mp3",
  "key:w3_q1_prompt": "/assets/audio/w3_q1_prompt.mp3",
  "Look at this pattern: 7, 12, 17, 22. What number is added each time to get the next term?": "/assets/audio/w3_q2_prompt.mp3",
  "key:w3_q2_prompt": "/assets/audio/w3_q2_prompt.mp3",
  "key:w3_q3_hint": "/assets/audio/w3_q3_hint.mp3",
  "key:w3_q2_hint": "/assets/audio/w3_q2_hint.mp3",
  "Look at this pattern: 9, 11, 13, 15. What number is added each time to get the next term?": "/assets/audio/w3_q3_prompt.mp3",
  "key:w3_q3_prompt": "/assets/audio/w3_q3_prompt.mp3",
  "Look at this pattern: 11, 17, 23, 29. What number is added each time to get the next term?": "/assets/audio/w3_q4_prompt.mp3",
  "key:w3_q4_prompt": "/assets/audio/w3_q4_prompt.mp3",
  "key:w3_q4_hint": "/assets/audio/w3_q4_hint.mp3",
  "key:w3_q5_hint": "/assets/audio/w3_q5_hint.mp3",
  "Look at this pattern: 3, 11, 19, 27. What number is added each time to get the next term?": "/assets/audio/w3_q5_prompt.mp3",
  "key:w3_q5_prompt": "/assets/audio/w3_q5_prompt.mp3",
  "Look at this pattern: 14, 18, 22, 26. What number is added each time to get the next term?": "/assets/audio/w3_q6_prompt.mp3",
  "key:w3_q6_prompt": "/assets/audio/w3_q6_prompt.mp3",
  "key:w3_q6_hint": "/assets/audio/w3_q6_hint.mp3",
  "key:w3_q7_hint": "/assets/audio/w3_q7_hint.mp3",
  "Look at this pattern: 13, 16, 19, 22. What number is added each time to get the next term?": "/assets/audio/w3_q8_prompt.mp3",
  "key:w3_q8_prompt": "/assets/audio/w3_q8_prompt.mp3",
  "Look at this pattern: 6, 15, 24, 33. What number is added each time to get the next term?": "/assets/audio/w3_q7_prompt.mp3",
  "key:w3_q7_prompt": "/assets/audio/w3_q7_prompt.mp3",
  "key:w3_q9_hint": "/assets/audio/w3_q9_hint.mp3",
  "key:w3_q8_hint": "/assets/audio/w3_q8_hint.mp3",
  "Look at this pattern: 5, 15, 25, 35. What number is added each time to get the next term?": "/assets/audio/w3_q10_prompt.mp3",
  "key:w3_q10_prompt": "/assets/audio/w3_q10_prompt.mp3",
  "Look at this pattern: 8, 15, 22, 29. What number is added each time to get the next term?": "/assets/audio/w3_q9_prompt.mp3",
  "key:w3_q9_prompt": "/assets/audio/w3_q9_prompt.mp3",
  "key:w3_q10_hint": "/assets/audio/w3_q10_hint.mp3",
  "A pattern starts at 5 and adds 6 each time. What is the value of the 5th term?": "/assets/audio/w4_q2_prompt.mp3",
  "key:w4_q2_prompt": "/assets/audio/w4_q2_prompt.mp3",
  "A pattern starts at 3 and adds 4 each time. What is the value of the 6th term?": "/assets/audio/w4_q1_prompt.mp3",
  "key:w4_q1_prompt": "/assets/audio/w4_q1_prompt.mp3",
  "Term = start + (position − 1) × step = 3 + (6 − 1) × 4.": "/assets/audio/w4_q1_hint.mp3",
  "key:w4_q1_hint": "/assets/audio/w4_q1_hint.mp3",
  "A pattern starts at 10 and adds 3 each time. What is the value of the 7th term?": "/assets/audio/w4_q4_prompt.mp3",
  "key:w4_q4_prompt": "/assets/audio/w4_q4_prompt.mp3",
  "A pattern starts at 2 and adds 7 each time. What is the value of the 8th term?": "/assets/audio/w4_q3_prompt.mp3",
  "key:w4_q3_prompt": "/assets/audio/w4_q3_prompt.mp3",
  "Term = start + (position − 1) × step = 2 + (8 − 1) × 7.": "/assets/audio/w4_q3_hint.mp3",
  "key:w4_q3_hint": "/assets/audio/w4_q3_hint.mp3",
  "Term = start + (position − 1) × step = 5 + (5 − 1) × 6.": "/assets/audio/w4_q2_hint.mp3",
  "key:w4_q2_hint": "/assets/audio/w4_q2_hint.mp3",
  "A pattern starts at 4 and adds 9 each time. What is the value of the 6th term?": "/assets/audio/w4_q6_prompt.mp3",
  "key:w4_q6_prompt": "/assets/audio/w4_q6_prompt.mp3",
  "A pattern starts at 6 and adds 5 each time. What is the value of the 9th term?": "/assets/audio/w4_q5_prompt.mp3",
  "key:w4_q5_prompt": "/assets/audio/w4_q5_prompt.mp3",
  "Term = start + (position − 1) × step = 6 + (9 − 1) × 5.": "/assets/audio/w4_q5_hint.mp3",
  "key:w4_q5_hint": "/assets/audio/w4_q5_hint.mp3",
  "Term = start + (position − 1) × step = 10 + (7 − 1) × 3.": "/assets/audio/w4_q4_hint.mp3",
  "key:w4_q4_hint": "/assets/audio/w4_q4_hint.mp3",
  "A pattern starts at 8 and adds 4 each time. What is the value of the 10th term?": "/assets/audio/w4_q7_prompt.mp3",
  "key:w4_q7_prompt": "/assets/audio/w4_q7_prompt.mp3",
  "Term = start + (position − 1) × step = 8 + (10 − 1) × 4.": "/assets/audio/w4_q7_hint.mp3",
  "key:w4_q7_hint": "/assets/audio/w4_q7_hint.mp3",
  "A pattern starts at 1 and adds 8 each time. What is the value of the 7th term?": "/assets/audio/w4_q8_prompt.mp3",
  "key:w4_q8_prompt": "/assets/audio/w4_q8_prompt.mp3",
  "Term = start + (position − 1) × step = 4 + (6 − 1) × 9.": "/assets/audio/w4_q6_hint.mp3",
  "key:w4_q6_hint": "/assets/audio/w4_q6_hint.mp3",
  "A pattern starts at 7 and adds 6 each time. What is the value of the 8th term?": "/assets/audio/w4_q10_prompt.mp3",
  "key:w4_q10_prompt": "/assets/audio/w4_q10_prompt.mp3",
  "A pattern starts at 9 and adds 2 each time. What is the value of the 11th term?": "/assets/audio/w4_q9_prompt.mp3",
  "key:w4_q9_prompt": "/assets/audio/w4_q9_prompt.mp3",
  "Term = start + (position − 1) × step = 9 + (11 − 1) × 2.": "/assets/audio/w4_q9_hint.mp3",
  "key:w4_q9_hint": "/assets/audio/w4_q9_hint.mp3",
  "Term = start + (position − 1) × step = 1 + (7 − 1) × 8.": "/assets/audio/w4_q8_hint.mp3",
  "key:w4_q8_hint": "/assets/audio/w4_q8_hint.mp3",
  "Each new figure adds 3 tiles to the one before it.": "/assets/audio/w5_q9_hint.mp3",
  "key:w5_q1_hint": "/assets/audio/w5_q1_hint.mp3",
  "Term = start + (position − 1) × step = 7 + (8 − 1) × 6.": "/assets/audio/w4_q10_hint.mp3",
  "key:w4_q10_hint": "/assets/audio/w4_q10_hint.mp3",
  "A tile pattern grows like this — Figure 1 has 3 tiles, Figure 2 has 7, Figure 3 has 11, Figure 4 has 15. How many tiles will Figure 5 have?": "/assets/audio/w5_q2_prompt.mp3",
  "key:w5_q2_prompt": "/assets/audio/w5_q2_prompt.mp3",
  "A tile pattern grows like this — Figure 1 has 4 tiles, Figure 2 has 7, Figure 3 has 10, Figure 4 has 13. How many tiles will Figure 5 have?": "/assets/audio/w5_q1_prompt.mp3",
  "key:w5_q1_prompt": "/assets/audio/w5_q1_prompt.mp3",
  "Each new figure adds 2 tiles to the one before it.": "/assets/audio/w5_q7_hint.mp3",
  "key:w5_q3_hint": "/assets/audio/w5_q3_hint.mp3",
  "Each new figure adds 4 tiles to the one before it.": "/assets/audio/w5_q2_hint.mp3",
  "key:w5_q2_hint": "/assets/audio/w5_q2_hint.mp3",
  "A tile pattern grows like this — Figure 1 has 5 tiles, Figure 2 has 7, Figure 3 has 9, Figure 4 has 11. How many tiles will Figure 5 have?": "/assets/audio/w5_q3_prompt.mp3",
  "key:w5_q3_prompt": "/assets/audio/w5_q3_prompt.mp3",
  "A tile pattern grows like this — Figure 1 has 2 tiles, Figure 2 has 7, Figure 3 has 12, Figure 4 has 17. How many tiles will Figure 5 have?": "/assets/audio/w5_q4_prompt.mp3",
  "key:w5_q4_prompt": "/assets/audio/w5_q4_prompt.mp3",
  "key:w5_q5_hint": "/assets/audio/w5_q5_hint.mp3",
  "Each new figure adds 5 tiles to the one before it.": "/assets/audio/w5_q8_hint.mp3",
  "key:w5_q4_hint": "/assets/audio/w5_q4_hint.mp3",
  "A tile pattern grows like this — Figure 1 has 6 tiles, Figure 2 has 9, Figure 3 has 12, Figure 4 has 15. How many tiles will Figure 5 have?": "/assets/audio/w5_q5_prompt.mp3",
  "key:w5_q5_prompt": "/assets/audio/w5_q5_prompt.mp3",
  "A tile pattern grows like this — Figure 1 has 1 tiles, Figure 2 has 7, Figure 3 has 13, Figure 4 has 19. How many tiles will Figure 5 have?": "/assets/audio/w5_q6_prompt.mp3",
  "key:w5_q6_prompt": "/assets/audio/w5_q6_prompt.mp3",
  "Each new figure adds 6 tiles to the one before it.": "/assets/audio/w5_q6_hint.mp3",
  "key:w5_q6_hint": "/assets/audio/w5_q6_hint.mp3",
  "key:w5_q7_hint": "/assets/audio/w5_q7_hint.mp3",
  "A tile pattern grows like this — Figure 1 has 3 tiles, Figure 2 has 8, Figure 3 has 13, Figure 4 has 18. How many tiles will Figure 5 have?": "/assets/audio/w5_q8_prompt.mp3",
  "key:w5_q8_prompt": "/assets/audio/w5_q8_prompt.mp3",
  "A tile pattern grows like this — Figure 1 has 7 tiles, Figure 2 has 9, Figure 3 has 11, Figure 4 has 13. How many tiles will Figure 5 have?": "/assets/audio/w5_q7_prompt.mp3",
  "key:w5_q7_prompt": "/assets/audio/w5_q7_prompt.mp3",
  "key:w5_q8_hint": "/assets/audio/w5_q8_hint.mp3",
  "key:w5_q9_hint": "/assets/audio/w5_q9_hint.mp3",
  "A tile pattern grows like this — Figure 1 has 8 tiles, Figure 2 has 11, Figure 3 has 14, Figure 4 has 17. How many tiles will Figure 5 have?": "/assets/audio/w5_q9_prompt.mp3",
  "key:w5_q9_prompt": "/assets/audio/w5_q9_prompt.mp3",
  "A tile pattern grows like this — Figure 1 has 2 tiles, Figure 2 has 9, Figure 3 has 16, Figure 4 has 23. How many tiles will Figure 5 have?": "/assets/audio/w5_q10_prompt.mp3",
  "key:w5_q10_prompt": "/assets/audio/w5_q10_prompt.mp3",
  "Each new figure adds 7 tiles to the one before it.": "/assets/audio/w5_q10_hint.mp3",
  "key:w5_q10_hint": "/assets/audio/w5_q10_hint.mp3",
  "Multiply the two choice counts — don't add them!": "/assets/audio/w6_q10_hint.mp3",
  "key:w6_q1_hint": "/assets/audio/w6_q1_hint.mp3",
  "A dessert stall offers 3 ice-cream flavours and 2 cone types. If you list every combination systematically, one at a time in order, how many combinations are possible in total?": "/assets/audio/w6_q1_prompt.mp3",
  "key:w6_q1_prompt": "/assets/audio/w6_q1_prompt.mp3",
  "A clothing shop offers 2 T-shirt colours and 4 shorts styles. If you list every combination systematically, one at a time in order, how many combinations are possible in total?": "/assets/audio/w6_q2_prompt.mp3",
  "key:w6_q2_prompt": "/assets/audio/w6_q2_prompt.mp3",
  "key:w6_q3_hint": "/assets/audio/w6_q3_hint.mp3",
  "key:w6_q2_hint": "/assets/audio/w6_q2_hint.mp3",
  "A sandwich bar offers 4 bread types and 2 filling options. If you list every combination systematically, one at a time in order, how many combinations are possible in total?": "/assets/audio/w6_q3_prompt.mp3",
  "key:w6_q3_prompt": "/assets/audio/w6_q3_prompt.mp3",
  "A pizzeria offers 3 pizza bases and 3 topping choices. If you list every combination systematically, one at a time in order, how many combinations are possible in total?": "/assets/audio/w6_q4_prompt.mp3",
  "key:w6_q4_prompt": "/assets/audio/w6_q4_prompt.mp3",
  "key:w6_q5_hint": "/assets/audio/w6_q5_hint.mp3",
  "key:w6_q4_hint": "/assets/audio/w6_q4_hint.mp3",
  "A phone store offers 2 phone case shapes and 3 colour options. If you list every combination systematically, one at a time in order, how many combinations are possible in total?": "/assets/audio/w6_q5_prompt.mp3",
  "key:w6_q5_prompt": "/assets/audio/w6_q5_prompt.mp3",
  "A library display offers 5 book genres and 2 cover styles. If you list every combination systematically, one at a time in order, how many combinations are possible in total?": "/assets/audio/w6_q6_prompt.mp3",
  "key:w6_q6_prompt": "/assets/audio/w6_q6_prompt.mp3",
  "key:w6_q7_hint": "/assets/audio/w6_q7_hint.mp3",
  "key:w6_q6_hint": "/assets/audio/w6_q6_hint.mp3",
  "A design app offers 2 wallpaper patterns and 5 colour tints. If you list every combination systematically, one at a time in order, how many combinations are possible in total?": "/assets/audio/w6_q8_prompt.mp3",
  "key:w6_q8_prompt": "/assets/audio/w6_q8_prompt.mp3",
  "A café offers 3 salad bases and 4 dressing choices. If you list every combination systematically, one at a time in order, how many combinations are possible in total?": "/assets/audio/w6_q7_prompt.mp3",
  "key:w6_q7_prompt": "/assets/audio/w6_q7_prompt.mp3",
  "key:w6_q9_hint": "/assets/audio/w6_q9_hint.mp3",
  "key:w6_q8_hint": "/assets/audio/w6_q8_hint.mp3",
  "A stationery shop offers 3 notebook covers and 2 page styles. If you list every combination systematically, one at a time in order, how many combinations are possible in total?": "/assets/audio/w6_q10_prompt.mp3",
  "key:w6_q10_prompt": "/assets/audio/w6_q10_prompt.mp3",
  "A video game offers 4 game characters and 3 costume skins. If you list every combination systematically, one at a time in order, how many combinations are possible in total?": "/assets/audio/w6_q9_prompt.mp3",
  "key:w6_q9_prompt": "/assets/audio/w6_q9_prompt.mp3",
  "key:w6_q10_hint": "/assets/audio/w6_q10_hint.mp3",
  "A tree diagram branches 2 ways, then each branch splits 3 ways, then each of those splits 2 ways.": "/assets/audio/w7_q1_hint.mp3",
  "key:w7_q1_hint": "/assets/audio/w7_q1_hint.mp3",
  "A sandwich shop offers 2 breads, 3 fillings, and 2 sauces. Drawing a tree diagram in your head, how many different total combinations are possible?": "/assets/audio/w7_q1_prompt.mp3",
  "key:w7_q1_prompt": "/assets/audio/w7_q1_prompt.mp3",
  "An ice-cream stall offers 3 cup sizes, 2 flavours, and 2 toppings. Drawing a tree diagram in your head, how many different total combinations are possible?": "/assets/audio/w7_q2_prompt.mp3",
  "key:w7_q2_prompt": "/assets/audio/w7_q2_prompt.mp3",
  "A tree diagram branches 2 ways, then each branch splits 2 ways, then each of those splits 3 ways.": "/assets/audio/w7_q3_hint.mp3",
  "key:w7_q3_hint": "/assets/audio/w7_q3_hint.mp3",
  "A tree diagram branches 3 ways, then each branch splits 2 ways, then each of those splits 2 ways.": "/assets/audio/w7_q2_hint.mp3",
  "key:w7_q2_hint": "/assets/audio/w7_q2_hint.mp3",
  "A bike shop offers 2 frame colours, 4 wheel types, and 2 seat styles. Drawing a tree diagram in your head, how many different total combinations are possible?": "/assets/audio/w7_q4_prompt.mp3",
  "key:w7_q4_prompt": "/assets/audio/w7_q4_prompt.mp3",
  "A door design app offers 2 paint colours, 2 handle styles, and 3 knob finishes. Drawing a tree diagram in your head, how many different total combinations are possible?": "/assets/audio/w7_q3_prompt.mp3",
  "key:w7_q3_prompt": "/assets/audio/w7_q3_prompt.mp3",
  "A tree diagram branches 3 ways, then each branch splits 3 ways, then each of those splits 2 ways.": "/assets/audio/w7_q5_hint.mp3",
  "key:w7_q5_hint": "/assets/audio/w7_q5_hint.mp3",
  "A tree diagram branches 2 ways, then each branch splits 4 ways, then each of those splits 2 ways.": "/assets/audio/w7_q4_hint.mp3",
  "key:w7_q4_hint": "/assets/audio/w7_q4_hint.mp3",
  "A burger stand offers 3 bun types, 3 patty choices, and 2 cheese options. Drawing a tree diagram in your head, how many different total combinations are possible?": "/assets/audio/w7_q5_prompt.mp3",
  "key:w7_q5_prompt": "/assets/audio/w7_q5_prompt.mp3",
  "A phone case app offers 2 case colours, 2 materials, and 4 sticker designs. Drawing a tree diagram in your head, how many different total combinations are possible?": "/assets/audio/w7_q6_prompt.mp3",
  "key:w7_q6_prompt": "/assets/audio/w7_q6_prompt.mp3",
  "A tree diagram branches 2 ways, then each branch splits 2 ways, then each of those splits 4 ways.": "/assets/audio/w7_q6_hint.mp3",
  "key:w7_q6_hint": "/assets/audio/w7_q6_hint.mp3",
  "A tree diagram branches 3 ways, then each branch splits 2 ways, then each of those splits 3 ways.": "/assets/audio/w7_q7_hint.mp3",
  "key:w7_q7_hint": "/assets/audio/w7_q7_hint.mp3",
  "A game lets you pick 2 body types, 3 hairstyles, and 3 outfits for your avatar. Drawing a tree diagram in your head, how many different total combinations are possible?": "/assets/audio/w7_q8_prompt.mp3",
  "key:w7_q8_prompt": "/assets/audio/w7_q8_prompt.mp3",
  "A dress designer offers 3 fabrics, 2 sleeve styles, and 3 patterns. Drawing a tree diagram in your head, how many different total combinations are possible?": "/assets/audio/w7_q7_prompt.mp3",
  "key:w7_q7_prompt": "/assets/audio/w7_q7_prompt.mp3",
  "A tree diagram branches 2 ways, then each branch splits 3 ways, then each of those splits 3 ways.": "/assets/audio/w7_q8_hint.mp3",
  "key:w7_q8_hint": "/assets/audio/w7_q8_hint.mp3",
  "A tree diagram branches 4 ways, then each branch splits 2 ways, then each of those splits 2 ways.": "/assets/audio/w7_q9_hint.mp3",
  "key:w7_q9_hint": "/assets/audio/w7_q9_hint.mp3",
  "You flip 2... a coin, then another coin, then a third coin. Drawing a tree diagram in your head, how many different total combinations are possible?": "/assets/audio/w7_q10_prompt.mp3",
  "key:w7_q10_prompt": "/assets/audio/w7_q10_prompt.mp3",
  "A bakery offers 4 cupcake flavours, 2 frostings, and 2 toppings. Drawing a tree diagram in your head, how many different total combinations are possible?": "/assets/audio/w7_q9_prompt.mp3",
  "key:w7_q9_prompt": "/assets/audio/w7_q9_prompt.mp3",
  "Multiply the number of options at every stage together.": "/assets/audio/w8_q10_hint.mp3",
  "key:w8_q1_hint": "/assets/audio/w8_q1_hint.mp3",
  "A tree diagram branches 2 ways, then each branch splits 2 ways, then each of those splits 2 ways.": "/assets/audio/w7_q10_hint.mp3",
  "key:w7_q10_hint": "/assets/audio/w7_q10_hint.mp3",
  "A suitcase lock has 3 dials, each showing digits 0 to 9 (10 options). How many different total possibilities are there?": "/assets/audio/w8_q2_prompt.mp3",
  "key:w8_q2_prompt": "/assets/audio/w8_q2_prompt.mp3",
  "A padlock has 2 dials. The first can show 9 symbols and the second can show 10 symbols. How many different total possibilities are there?": "/assets/audio/w8_q1_prompt.mp3",
  "key:w8_q1_prompt": "/assets/audio/w8_q1_prompt.mp3",
  "key:w8_q3_hint": "/assets/audio/w8_q3_hint.mp3",
  "key:w8_q2_hint": "/assets/audio/w8_q2_hint.mp3",
  "A toy lock has 3 dials, each showing 5 different symbols. How many different total possibilities are there?": "/assets/audio/w8_q4_prompt.mp3",
  "key:w8_q4_prompt": "/assets/audio/w8_q4_prompt.mp3",
  "An airport lounge code uses 2 letters, each from a 26-letter alphabet. How many different total possibilities are there?": "/assets/audio/w8_q3_prompt.mp3",
  "key:w8_q3_prompt": "/assets/audio/w8_q3_prompt.mp3",
  "key:w8_q4_hint": "/assets/audio/w8_q4_hint.mp3",
  "key:w8_q5_hint": "/assets/audio/w8_q5_hint.mp3",
  "A 2-digit display shows a first digit with 10 options and a second with 9 lit options. How many different total possibilities are there?": "/assets/audio/w8_q6_prompt.mp3",
  "key:w8_q6_prompt": "/assets/audio/w8_q6_prompt.mp3",
  "A vending machine menu has 4 snack rows and 3 columns per row to choose from. How many different total possibilities are there?": "/assets/audio/w8_q5_prompt.mp3",
  "key:w8_q5_prompt": "/assets/audio/w8_q5_prompt.mp3",
  "key:w8_q6_hint": "/assets/audio/w8_q6_hint.mp3",
  "key:w8_q7_hint": "/assets/audio/w8_q7_hint.mp3",
  "You roll 3 dice, each with 6 faces. How many different total possibilities are there?": "/assets/audio/w8_q7_prompt.mp3",
  "key:w8_q7_prompt": "/assets/audio/w8_q7_prompt.mp3",
  "You roll 2 eight-sided dice. How many different total possibilities are there?": "/assets/audio/w8_q8_prompt.mp3",
  "key:w8_q8_prompt": "/assets/audio/w8_q8_prompt.mp3",
  "key:w8_q8_hint": "/assets/audio/w8_q8_hint.mp3",
  "key:w8_q9_hint": "/assets/audio/w8_q9_hint.mp3",
  "A toy robot code has 4 buttons, each with 3 possible settings. How many different total possibilities are there?": "/assets/audio/w8_q10_prompt.mp3",
  "key:w8_q10_prompt": "/assets/audio/w8_q10_prompt.mp3",
  "A 2-digit PIN uses digits 0 to 9 for each of its 2 positions. How many different total possibilities are there?": "/assets/audio/w8_q9_prompt.mp3",
  "key:w8_q9_prompt": "/assets/audio/w8_q9_prompt.mp3",
  "key:w8_q10_hint": "/assets/audio/w8_q10_hint.mp3",
  "Once one item is used, it can't be used again — so the choices shrink by 1 each step.": "/assets/audio/w9_q10_hint.mp3",
  "key:w9_q1_hint": "/assets/audio/w9_q1_hint.mp3",
  "Using the digits 1, 2, 3 with no digit repeated, how many different 2-digit numbers can you form?": "/assets/audio/w9_q1_prompt.mp3",
  "key:w9_q1_prompt": "/assets/audio/w9_q1_prompt.mp3",
  "From 4 friends, how many ways can you pick a Captain and a Vice-Captain (2 different roles)?": "/assets/audio/w9_q2_prompt.mp3",
  "key:w9_q2_prompt": "/assets/audio/w9_q2_prompt.mp3",
  "From 4 medal contenders, how many ways can Gold, Silver, and Bronze be awarded?": "/assets/audio/w9_q4_prompt.mp3",
  "key:w9_q4_prompt": "/assets/audio/w9_q4_prompt.mp3",
  "key:w9_q2_hint": "/assets/audio/w9_q2_hint.mp3",
  "key:w9_q3_hint": "/assets/audio/w9_q3_hint.mp3",
  "In how many different orders can 3 runners finish a race (1st, 2nd, 3rd — no ties)?": "/assets/audio/w9_q3_prompt.mp3",
  "key:w9_q3_prompt": "/assets/audio/w9_q3_prompt.mp3",
  "In how many different orders can 4 books be arranged in a row on a shelf?": "/assets/audio/w9_q6_prompt.mp3",
  "key:w9_q6_prompt": "/assets/audio/w9_q6_prompt.mp3",
  "key:w9_q4_hint": "/assets/audio/w9_q4_hint.mp3",
  "key:w9_q5_hint": "/assets/audio/w9_q5_hint.mp3",
  "Using the letters A, B, C, D, E with no repeats, how many different 2-letter codes can you form?": "/assets/audio/w9_q5_prompt.mp3",
  "key:w9_q5_prompt": "/assets/audio/w9_q5_prompt.mp3",
  "From 5 sprinters, how many ways can 1st, 2nd, and 3rd place be awarded?": "/assets/audio/w9_q7_prompt.mp3",
  "key:w9_q7_prompt": "/assets/audio/w9_q7_prompt.mp3",
  "key:w9_q6_hint": "/assets/audio/w9_q6_hint.mp3",
  "key:w9_q7_hint": "/assets/audio/w9_q7_hint.mp3",
  "A locker uses 2 different digits chosen from 1, 2, 3 (no repeats). How many locker codes are possible?": "/assets/audio/w9_q8_prompt.mp3",
  "key:w9_q8_prompt": "/assets/audio/w9_q8_prompt.mp3",
  "In how many different orders can 4 of 5 friends line up for a photo (no repeats)?": "/assets/audio/w9_q10_prompt.mp3",
  "key:w9_q10_prompt": "/assets/audio/w9_q10_prompt.mp3",
  "key:w9_q9_hint": "/assets/audio/w9_q9_hint.mp3",
  "key:w9_q8_hint": "/assets/audio/w9_q8_hint.mp3",
  "From 6 students, how many ways can you choose a Team Leader and a Note-Taker (2 different roles)?": "/assets/audio/w9_q9_prompt.mp3",
  "key:w9_q9_prompt": "/assets/audio/w9_q9_prompt.mp3",
  "key:w9_q10_hint": "/assets/audio/w9_q10_hint.mp3",
  "Step = 8 seats per row. Term = 20 + (8 − 1) × 8.": "/assets/audio/w10_q1_hint.mp3",
  "key:w10_q1_hint": "/assets/audio/w10_q1_hint.mp3",
  "A café menu has 4 mains, 3 sides, and 2 drinks. Using a systematic list, how many complete 3-course meals can be made?": "/assets/audio/w10_q2_prompt.mp3",
  "key:w10_q2_prompt": "/assets/audio/w10_q2_prompt.mp3",
  "A stadium's rows grow by a fixed number of seats: Row 1 has 20 seats, Row 2 has 28, Row 3 has 36. How many seats are in Row 8?": "/assets/audio/w10_q1_prompt.mp3",
  "key:w10_q1_prompt": "/assets/audio/w10_q1_prompt.mp3",
  "Multiply all three choice counts together.": "/assets/audio/w10_q2_hint.mp3",
  "key:w10_q2_hint": "/assets/audio/w10_q2_hint.mp3",
  "Step = $8. Term = 15 + (12 − 1) × 8.": "/assets/audio/w10_q3_hint.mp3",
  "key:w10_q3_hint": "/assets/audio/w10_q3_hint.mp3",
  "A password uses 3 different letters chosen from A, B, C, D, E (no letter repeated). How many different passwords are possible?": "/assets/audio/w10_q4_prompt.mp3",
  "key:w10_q4_prompt": "/assets/audio/w10_q4_prompt.mp3",
  "A savings jar starts with $15 and gains a fixed amount every week: $15, $23, $31, $39. How much will be in the jar after 12 weeks (the 12th term)?": "/assets/audio/w10_q3_prompt.mp3",
  "key:w10_q3_prompt": "/assets/audio/w10_q3_prompt.mp3",
  "Step size = 4 tiles. Term = 5 + (6 − 1) × 4.": "/assets/audio/w10_q5_hint.mp3",
  "key:w10_q5_hint": "/assets/audio/w10_q5_hint.mp3",
  "Once a letter is used, there is one fewer option for the next spot: 5 × 4 × 3.": "/assets/audio/w10_q4_hint.mp3",
  "key:w10_q4_hint": "/assets/audio/w10_q4_hint.mp3",
  "A staircase pattern of tiles grows: Step 1 uses 5 tiles, Step 2 uses 9, Step 3 uses 13. How many tiles will Step 6 use?": "/assets/audio/w10_q5_prompt.mp3",
  "key:w10_q5_prompt": "/assets/audio/w10_q5_prompt.mp3",
  "A theme park wristband can be 1 of 6 colours, paired with 1 of 4 charm designs. A systematic list is being made of every colour-charm pair. How many pairs are on the list in total?": "/assets/audio/w10_q6_prompt.mp3",
  "key:w10_q6_prompt": "/assets/audio/w10_q6_prompt.mp3",
  "Multiply the number of colours by the number of charms.": "/assets/audio/w10_q6_hint.mp3",
  "key:w10_q6_hint": "/assets/audio/w10_q6_hint.mp3",
  "Step = 25cm. Term = 30 + (9 − 1) × 25.": "/assets/audio/w10_q7_hint.mp3",
  "key:w10_q7_hint": "/assets/audio/w10_q7_hint.mp3",
  "A relay team of 4 sprinters must run in some order, and the coach wants to try every possible running order (no repeats). How many orders are there to list?": "/assets/audio/w10_q8_prompt.mp3",
  "key:w10_q8_prompt": "/assets/audio/w10_q8_prompt.mp3",
  "A ladder's rungs are spaced evenly: rung 1 is at 30cm, rung 2 at 55cm, rung 3 at 80cm. At what height is rung 9?": "/assets/audio/w10_q7_prompt.mp3",
  "key:w10_q7_prompt": "/assets/audio/w10_q7_prompt.mp3",
  "4 choices for 1st, then 3 left for 2nd, then 2, then 1.": "/assets/audio/w10_q8_hint.mp3",
  "key:w10_q8_hint": "/assets/audio/w10_q8_hint.mp3",
  "Multiply all three factors: candles × scents × boxes.": "/assets/audio/w10_q9_hint.mp3",
  "key:w10_q9_hint": "/assets/audio/w10_q9_hint.mp3",
  "A gift shop is bundling 3 types of candles with 5 scent options and 2 box styles into a systematic gift-list. How many different gift bundles are on the list?": "/assets/audio/w10_q9_prompt.mp3",
  "key:w10_q9_prompt": "/assets/audio/w10_q9_prompt.mp3",
  "A plant's height is measured weekly and grows by a fixed amount: Week 1 = 4cm, Week 2 = 10cm, Week 3 = 16cm. In which week will the plant first reach exactly 46cm?": "/assets/audio/w10_q10_prompt.mp3",
  "key:w10_q10_prompt": "/assets/audio/w10_q10_prompt.mp3",
  "Step = 6cm. Solve 4 + (n − 1) × 6 = 46 for n.": "/assets/audio/w10_q10_hint.mp3",
  "key:w10_q10_hint": "/assets/audio/w10_q10_hint.mp3"
};
export default audioMap;
